_wandb:
    value:
        cli_version: 0.22.1
        e:
            qtbwa1v4vpi8kxpy6apf01d5vcytp9oi:
                args:
                    - --users
                    - configs/users.json
                    - --k
                    - "5"
                    - --style
                    - all
                email: hwanseok0629@gmail.com
                executable: /opt/anaconda3/bin/python
                host: hwan-MacBook-Pro.local
                os: macOS-15.6.1-arm64-arm-64bit
                program: -m src.pipelines.eval_report
                python: CPython 3.12.4
                root: /Users/hwanseok/Documents/mlops-cloud-project-mlops-6
                startedAt: "2025-10-01T02:38:46.280559Z"
                writerId: qtbwa1v4vpi8kxpy6apf01d5vcytp9oi
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.12.4
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
