name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 & 푸시
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hwan00/wine-reco:latest

  # (선택) 배포 단계
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull hwan00/wine-reco:latest
            docker rm -f wine-reco-api || true
            docker run -d -p 8000:8000 \
              -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} \
              -e WANDB_ENTITY=hwanseok0629- \
              -e WANDB_PROJECT=wine-reco \
              --name wine-reco-api hwan00/wine-reco:latest
